FREE_TIER_SNIPPET_LIMIT = 50
FREE_TIER_NOTE_LIMIT = 10
FREE_TIER_PROJECT_LIMIT = 3
FREE_TIER_AI_MESSAGES_PER_DAY = 20
FREE_TIER_README_PER_MONTH = 3
PRO_TIER_AI_MESSAGES_PER_MONTH = 500
AI_PROVIDER_MAX_INPUT_CHARS = 30000
AI_PROVIDER_MAX_MESSAGE_CHARS = 12000
AI_PROVIDER_MAX_OUTPUT_TOKENS = 1400


PRO_TIER_PRICE_USD = 6.00


MAX_FAILED_LOGIN_ATTEMPTS = 5
ACCOUNT_LOCK_DURATION_MINUTES = 15
PASSWORD_MIN_LENGTH = 8
LOGIN_RATE_LIMIT = "10/minute"


ACCESS_TOKEN_EXPIRE_MINUTES = 15
REFRESH_TOKEN_EXPIRE_DAYS = 30
EMAIL_VERIFY_TOKEN_EXPIRE_HOURS = 24
PASSWORD_RESET_TOKEN_EXPIRE_HOURS = 1


DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100


MAX_SEARCH_RESULTS = 50
SEARCH_MIN_QUERY_LENGTH = 2


MAX_AVATAR_SIZE_MB = 2
MAX_SNIPPET_SIZE_KB = 500


AI_MAX_CONTEXT_MESSAGES = 10
AI_MAX_TOKENS = 2000


FREE_TIER_COMPILER_FILE_LIMIT = 25
PRO_TIER_COMPILER_FILE_LIMIT = 250
FREE_TIER_COMPILER_RUNS_PER_DAY = 20
PRO_TIER_COMPILER_RUNS_PER_DAY = 200
COMPILER_MAX_CODE_CHARS = 120000
COMPILER_MAX_STDIN_CHARS = 12000
COMPILER_MAX_OUTPUT_CHARS = 20000
COMPILER_TIMEOUT_SECONDS = 5

TRASH_RETENTION_DAYS = 30


RAW_LOG_RETENTION_DAYS = 30
AGGREGATED_LOG_RETENTION_DAYS = 90
